# Linker script makes sure your variables go in the right place
# Again, there is basically no justice in this world so you cant predict where the .ld is
# Scattershot that bitch
if (NOT LINKER_SCRIPT)
	set(MEMMAP_SEARCH_DIRS
		"." "./MDK-ARM" 
		"./lib/f4/mem" "./src/mem")
	message("Looking for Linker Script in ${MEMMAP_SEARCH_DIRS}")
	find_file(LINKER_SCRIPT "${STM32FXXX}.ld" ${MEMMAP_SEARCH_DIRS}
		NO_CMAKE_PATH NO_CMAKE_ENVIRONMENT_PATH NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH)
	find_file(LINKER_SCRIPT "${STM32_SERIES_B}.ld" ${MEMMAP_SEARCH_DIRS}
		NO_CMAKE_PATH NO_CMAKE_ENVIRONMENT_PATH NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH)
	find_file(LINKER_SCRIPT "${STM32_SERIES_A}.ld" ${MEMMAP_SEARCH_DIRS}
		NO_CMAKE_PATH NO_CMAKE_ENVIRONMENT_PATH NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH)
	find_file(LINKER_SCRIPT "${STM32_SERIES}.ld" ${MEMMAP_SEARCH_DIRS}
		NO_CMAKE_PATH NO_CMAKE_ENVIRONMENT_PATH NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH)
	find_file(LINKER_SCRIPT "${STM32_FAMILY}.ld" ${MEMMAP_SEARCH_DIRS}
		NO_CMAKE_PATH NO_CMAKE_ENVIRONMENT_PATH NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH)
	find_file(LINKER_SCRIPT "${STM32FXXX}Tx_FLASH.ld" ${MEMMAP_SEARCH_DIRS}
		NO_CMAKE_PATH NO_CMAKE_ENVIRONMENT_PATH NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH)
	find_file(LINKER_SCRIPT "${STM32_SERIES_B}Tx_FLASH.ld" ${MEMMAP_SEARCH_DIRS}
		NO_CMAKE_PATH NO_CMAKE_ENVIRONMENT_PATH NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH)
	find_file(LINKER_SCRIPT "${STM32_SERIES_A}Tx_FLASH.ld" ${MEMMAP_SEARCH_DIRS}
		NO_CMAKE_PATH NO_CMAKE_ENVIRONMENT_PATH NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH)

	if (CUBE_PROJECT OR CUBE_PROJECT_LL)
		file(GLOB LINKER_SCRIPT "${STM32_FAMILY}*.ld")
	endif()
endif()
